//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMonitor_GUI.Properties
{


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
	{

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default
		{
			get
			{
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1280")]
		public double MainWindow_Width
		{
			get
			{
				return ((double)(this["MainWindow_Width"]));
			}
			set
			{
				this["MainWindow_Width"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("720")]
		public double MainWindow_Height
		{
			get
			{
				return ((double)(this["MainWindow_Height"]));
			}
			set
			{
				this["MainWindow_Height"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("200")]
		public double MainWindow_Left
		{
			get
			{
				return ((double)(this["MainWindow_Left"]));
			}
			set
			{
				this["MainWindow_Left"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("100")]
		public double MainWindow_Top
		{
			get
			{
				return ((double)(this["MainWindow_Top"]));
			}
			set
			{
				this["MainWindow_Top"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31.9162754963")]
		public double Lat
		{
			get
			{
				return ((double)(this["Lat"]));
			}
			set
			{
				this["Lat"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118.8053374789")]
		public double Lng
		{
			get
			{
				return ((double)(this["Lng"]));
			}
			set
			{
				this["Lng"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
		public string CoreIPaddress
		{
			get
			{
				return ((string)(this["CoreIPaddress"]));
			}
			set
			{
				this["CoreIPaddress"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("53799")]
		public int CorePort
		{
			get
			{
				return ((int)(this["CorePort"]));
			}
			set
			{
				this["CorePort"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("COM0")]
		public string COMPort
		{
			get
			{
				return ((string)(this["COMPort"]));
			}
			set
			{
				this["COMPort"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("66")]
		public int AlertLink
		{
			get
			{
				return ((int)(this["AlertLink"]));
			}
			set
			{
				this["AlertLink"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("66")]
		public int AlertRCrec
		{
			get
			{
				return ((int)(this["AlertRCrec"]));
			}
			set
			{
				this["AlertRCrec"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("3.4")]
		public double VoltageMin
		{
			get
			{
				return ((double)(this["VoltageMin"]));
			}
			set
			{
				this["VoltageMin"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("4.2")]
		public double VoltageMax
		{
			get
			{
				return ((double)(this["VoltageMax"]));
			}
			set
			{
				this["VoltageMax"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("3.7")]
		public double AlertVoltage
		{
			get
			{
				return ((double)(this["AlertVoltage"]));
			}
			set
			{
				this["AlertVoltage"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("20")]
		public int PowerStatus_level3
		{
			get
			{
				return ((int)(this["PowerStatus_level3"]));
			}
			set
			{
				this["PowerStatus_level3"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("10")]
		public int PowerStatus_level2
		{
			get
			{
				return ((int)(this["PowerStatus_level2"]));
			}
			set
			{
				this["PowerStatus_level2"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("5")]
		public int PowerStatus_level1
		{
			get
			{
				return ((int)(this["PowerStatus_level1"]));
			}
			set
			{
				this["PowerStatus_level1"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("30")]
		public int FlightLogReplyWait
		{
			get
			{
				return ((int)(this["FlightLogReplyWait"]));
			}
			set
			{
				this["FlightLogReplyWait"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("15")]
		public int FlightPlanReplyWait
		{
			get
			{
				return ((int)(this["FlightPlanReplyWait"]));
			}
			set
			{
				this["FlightPlanReplyWait"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public double Waypoint_Speed
		{
			get
			{
				return ((double)(this["Waypoint_Speed"]));
			}
			set
			{
				this["Waypoint_Speed"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool Initialization
		{
			get
			{
				return ((bool)(this["Initialization"]));
			}
			set
			{
				this["Initialization"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool AlertLinkSound
		{
			get
			{
				return ((bool)(this["AlertLinkSound"]));
			}
			set
			{
				this["AlertLinkSound"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool AlertVoltageSound
		{
			get
			{
				return ((bool)(this["AlertVoltageSound"]));
			}
			set
			{
				this["AlertVoltageSound"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool AlertLinkView
		{
			get
			{
				return ((bool)(this["AlertLinkView"]));
			}
			set
			{
				this["AlertLinkView"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool AlertVoltageView
		{
			get
			{
				return ((bool)(this["AlertVoltageView"]));
			}
			set
			{
				this["AlertVoltageView"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1.2.1")]
		public string XMonitorVersion
		{
			get
			{
				return ((string)(this["XMonitorVersion"]));
			}
			set
			{
				this["XMonitorVersion"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("3.4.1")]
		public string APFCVersion
		{
			get
			{
				return ((string)(this["APFCVersion"]));
			}
			set
			{
				this["APFCVersion"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("7")]
		public int AlertGPS
		{
			get
			{
				return ((int)(this["AlertGPS"]));
			}
			set
			{
				this["AlertGPS"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool AlertGPSView
		{
			get
			{
				return ((bool)(this["AlertGPSView"]));
			}
			set
			{
				this["AlertGPSView"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public double LatSub
		{
			get
			{
				return ((double)(this["LatSub"]));
			}
			set
			{
				this["LatSub"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public double LngSub
		{
			get
			{
				return ((double)(this["LngSub"]));
			}
			set
			{
				this["LngSub"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("国土地理院地図(航空)")]
		public string Provider
		{
			get
			{
				return ((string)(this["Provider"]));
			}
			set
			{
				this["Provider"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::Config.ConfigData ConfigRecord
		{
			get
			{
				return ((global::Config.ConfigData)(this["ConfigRecord"]));
			}
			set
			{
				this["ConfigRecord"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("30")]
		public int AlertRepeatTime
		{
			get
			{
				return ((int)(this["AlertRepeatTime"]));
			}
			set
			{
				this["AlertRepeatTime"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public long ACSLMessageNumber
		{
			get
			{
				return ((long)(this["ACSLMessageNumber"]));
			}
			set
			{
				this["ACSLMessageNumber"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("08/07/2015 22:28:00")]
		public global::System.DateTime ACSLMessageDate
		{
			get
			{
				return ((global::System.DateTime)(this["ACSLMessageDate"]));
			}
			set
			{
				this["ACSLMessageDate"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool ACSLMessageFlag
		{
			get
			{
				return ((bool)(this["ACSLMessageFlag"]));
			}
			set
			{
				this["ACSLMessageFlag"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool AlertGPSSound
		{
			get
			{
				return ((bool)(this["AlertGPSSound"]));
			}
			set
			{
				this["AlertGPSSound"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("xxx")]
		public string Function1
		{
			get
			{
				return ((string)(this["Function1"]));
			}
			set
			{
				this["Function1"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("xxx")]
		public string Function2
		{
			get
			{
				return ((string)(this["Function2"]));
			}
			set
			{
				this["Function2"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("xxx")]
		public string Function3
		{
			get
			{
				return ((string)(this["Function3"]));
			}
			set
			{
				this["Function3"] = value;
			}
		}

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PortName
        {
            get
            {
                return ((int)(this["PortName"]));
            }
            set
            {
                this["PortName"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Send1
        {
            get
            {
                return ((string)(this["Send1"]));
            }
            set
            {
                this["Send1"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Send2
        {
            get
            {
                return ((string)(this["Send2"]));
            }
            set
            {
                this["Send2"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int BaudRate
        {
            get
            {
                return ((int)(this["BaudRate"]));
            }
            set
            {
                this["BaudRate"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Waypoint_Threashold_X
        {
            get
            {
                return ((double)(this["Waypoint_Threashold"]));
            }
            set
            {
                this["Waypoint_Threashold"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Waypoint_Wait_X
        {
            get
            {
                return ((double)(this["Waypoint_Wait"]));
            }
            set
            {
                this["Waypoint_Wait"] = value;
            }
        }
	}
}
