/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Tue, Jan 22, 2008                                     */
/*  DESCRIPTION :Aliases of Integer Type                               */
/*  CPU TYPE    :SH7211                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/

//
//		'08/10/08	VC6.0Ç≈Ç‡ì«Ç›çûÇﬂÇÈÇÊÇ§Ç…èCê≥
//		'13/03/23	Win32 êÍópÇ…ïœçX
//

#ifndef INCLUDED_TYPEDEFINE_H
#define INCLUDED_TYPEDEFINE_H

typedef signed char _SBYTE;
typedef unsigned char _UBYTE;
typedef signed short _SWORD;
typedef unsigned short _UWORD;
typedef signed long _SDWORD;
typedef unsigned long _UDWORD;
typedef signed long long _SQWORD;
typedef unsigned long long _UQWORD;

typedef signed int _SINT;
typedef unsigned int _UINT;

#endif